FROM python:3.12-slim
COPY .env .env
COPY src_web/requirements.txt src_web/requirements.txt
RUN ls -lrt
WORKDIR /src_web
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "flask_server.py"]